T02: Implemented
LogeshTMM/Practice pull request #13
Opened 2023-08-31 04:57 UTC by LogeshTMM

2023-10-20 04:41 UTC, priyarathna requested changes

2023-10-20 04:41 UTC, priyarathna commented on T02/Program.cs
> +      var numString = num.ToString ();
num.ToString() is same as Console.ReadLine (). Use it.

2023-10-20 04:41 UTC, priyarathna commented on T02/Program.cs
> +﻿// CONVERT THE GIVEN NUMBER INTO WORD FORMAT AND ROMAN NUMERALS FORMAT
The output is right but the code is too complicated. Check [Karthick's](https://github.com/karthick-1205/Assignments/pull/35/files) for the simpler one.

2023-10-31 04:21 UTC, priyarathna requested changes

2023-10-31 04:21 UTC, priyarathna commented on T02/Program.cs
> +internal class Program {
Check column length and the output line is not relevant.

2023-11-17 05:50 UTC, priyarathna requested changes

2023-11-17 05:50 UTC, priyarathna commented on T02/Program.cs
> +      } else if (arr[2] != 0 && arr[3] >= 1) Console.Write (dic[arr[2] * 10] + dic[arr[3]]);
No else needed as return is used.

2023-11-21 05:14 UTC, priyarathna requested changes

2023-11-21 05:14 UTC, priyarathna commented on T02/Program.cs
> +      if (dic.TryGetValue (Convert.ToInt32 (temp), out string value)) Console.Write (value);
No need of 'return' here?

2023-11-23 04:59 UTC, LogeshTMM commented on T02/Program.cs
> +      if (dic.TryGetValue (Convert.ToInt32 (temp), out string value)) Console.Write (value);
I didn't use it here.

2023-11-28 05:10 UTC, priyarathna approved these changes

2023-11-28 05:10 UTC, merged