T07 implemented
LogeshTMM/Practice pull request #35
Opened 2023-11-02 04:22 UTC by LogeshTMM

2023-11-06 11:18 UTC, asfar-nazar requested changes
There is a gap between \u2501 and the next \u250f. You'll have to use u2533 and similar chars

![image](https://github.com/LogeshTMM/Practice/assets/86363064/1c883ae7-7e6e-4480-94dc-bf06b27eaee2)

2023-11-07 05:30 UTC, asfar-nazar requested changes
Change pull request title as per the announcement yesterday. Also the space to the left and right of the chess pieces are not the same.

2023-11-07 05:34 UTC, LogeshTMM commented
> Change pull request title as per the announcement yesterday. Also the space to the left and right of the chess pieces are not the same.

can you share the output images.

2023-11-09 05:00 UTC, asfar-nazar approved these changes

2023-11-09 05:00 UTC, closed without merging